[project]
name = "mfnwt"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-arm64", "osx-64"]
version = "1.3.0"

[dependencies]
filelock = "*"
meson = ">=1.3.1"
ninja = "*"
# modflow-devtools = ">=1.7.0,<2"

[tasks]
# install
install-devtools = "pip install --disable-pip-version-check git+https://github.com/MODFLOW-ORG/modflow-devtools.git"
install = { depends-on = [
    "install-devtools",
] }

# meson build for mfnwt
clean = { cmd = "rm -rf builddir" }
setup = { cmd = "meson setup --prefix=$(pwd) --bindir=bin builddir", env = { PKG_CONFIG_PATH = "$CONDA_PREFIX/lib/pkgconfig" } }
build = "meson install -C builddir"

# test mfnwt
test = { cmd = "meson test --verbose --no-rebuild -C builddir version" }

# get ostag for system
get-ostag = { cmd = "python -c 'from modflow_devtools.ostags import get_ostag; print(get_ostag())'"}
